require("svelte/register");
const glob = require("tiny-glob");
const { writeFileSync } = require("fs");
const { join } = require("path");
const { basename, dirname } = require("path");

(async function getPosts() {
  const postFiles = await glob("src/posts/**/*.svelte", {
    absolute: true
  });
  let imports = "";
  const modules = [];
  const meta = [];
  for (let file of postFiles) {
    const post = require(file);
    const slug = basename(dirname(file));
    if (!post || !post.meta || !post.meta.published) {
      continue;
    }
    const dateParts = post.meta.published.split("-").slice(0, 2);
    const component = `post_${dateParts.join("_")}_${slug}`;
    post.meta.id = component;
    post.meta.link = `/${dateParts.join("/")}/${slug}`;
    meta.push(post.meta);
    modules.push(component);
    imports += `import ${component} from "${file}"\n`;
  }

  writeFileSync(
    join(__dirname, "node_modules/posts.js"),
    `/** autogenerated by src/posts.js */\n${imports}
export const posts = {${modules.join(", ")}}
export const meta = ${JSON.stringify(meta)}
`
  );
})();
